dbeaver/dbeaver-devops#1810 Fixed backup and restore trusted certs and workspaces

diff --git a/manager/dbeaver-te b/manager/dbeaver-te
--- a/manager/dbeaver-te
+++ b/manager/dbeaver-te
@@ -389,7 +389,7 @@ createBackup(){
     done
 
     for SERVICE in $services; do
-        VOLUME_PATH=$(docker inspect -f '{{ range .Mounts }}{{ if eq .Type "volume" }}{{ println .Destination }}{{ end }}{{ end }}' $PROJECT_NAME-"$SERVICE"-1 | head -1)
+        VOLUME_PATH=$(docker inspect -f '{{ range .Mounts }}{{ if eq .Type "volume" }}{{ println .Destination }}{{ end }}{{ end }}' $PROJECT_NAME-"$SERVICE"-1 | grep '/workspace$')
 		docker compose exec -T $SERVICE sh -c "if [ -d '${VOLUME_PATH}' ] && [ \"\$(ls -A ${VOLUME_PATH})\" ]; then tar -czf - -C ${VOLUME_PATH} .;fi" > $BACKUP_PATH/"$SERVICE".tar.gz
 
     done
@@ -407,6 +407,11 @@ createBackup(){
 
 		CERT_PATH="${CERT_BASE_PATH%/*}"
 		tar -czf "$BACKUP_PATH/cert.tar.gz" -C "$CERT_PATH" .
+
+		TRUSTED_CERT_VOLUME_PATH="/opt/cloudbeaver/conf/certificates/custom"
+		docker compose exec -T cloudbeaver-te sh -c \
+			"if [ -d '${TRUSTED_CERT_VOLUME_PATH}' ] && [ \"\$(ls -A '${TRUSTED_CERT_VOLUME_PATH}')\" ]; then tar -czf - -C '${TRUSTED_CERT_VOLUME_PATH}' .; fi" \
+			> "$BACKUP_PATH/trusted-cacerts.tar.gz"
 	fi
 
     tar -czf "$BACKUP_PATH".tar.gz $BACKUP_PATH
@@ -425,17 +430,23 @@ restoreBackup(){
     BACKUP_DIR="$TEMP_DIR/backup/$BACKUP_FOLDER_NAME"
     ARCHIVE_DATE=$(echo $ARCHIVE_NAME | grep -o '[0-9]\{8\}')
 
-    services="cloudbeaver-dc cloudbeaver-qm cloudbeaver-rm cloudbeaver-te"
+    services="cloudbeaver-dc cloudbeaver-tm cloudbeaver-rm"
     for SERVICE in $services; do
         BACKUP_ARCHIVE_PATH="$BACKUP_DIR/${SERVICE}.tar.gz"
-        VOLUME_PATH=$(docker inspect -f '{{ range .Mounts }}{{ if eq .Type "volume" }}{{ println .Destination }}{{ end }}{{ end }}' $PROJECT_NAME-"$SERVICE"-1 | head -1)
+        VOLUME_PATH=$(docker inspect -f '{{ range .Mounts }}{{ if eq .Type "volume" }}{{ println .Destination }}{{ end }}{{ end }}' $PROJECT_NAME-"$SERVICE"-1 | grep '/workspace$')
         if [ -f "$BACKUP_ARCHIVE_PATH" ]; then
             echo "Restoring $SERVICE..."
 			docker cp $BACKUP_ARCHIVE_PATH $PROJECT_NAME-"$SERVICE"-1:/tmp/${SERVICE}.tar.gz
-			docker compose exec -T $SERVICE tar -xzvf /tmp/${SERVICE}.tar.gz -C $VOLUME_PATH
+			docker compose exec -T $SERVICE tar -xzvf /tmp/${SERVICE}.tar.gz -C $VOLUME_PATH || { 
+				echo "Error restoring $SERVICE workspace!"
+				printSupportMessage
+				exit 1
+			}
 			docker compose exec -T $SERVICE rm /tmp/${SERVICE}.tar.gz
         else
             echo "Backup archive $BACKUP_ARCHIVE_PATH not found."
+			printSupportMessage
+			exit 1
         fi
     done
 
@@ -445,21 +456,50 @@ restoreBackup(){
         docker exec -i $PROJECT_NAME-"postgres"-1 pg_restore --dbname cloudbeaver --username $CLOUDBEAVER_DB_USER --clean --if-exists < "$DB_BACKUP"
     else
         echo "PostgreSQL backup file not found."
+		printSupportMessage
+		exit 1
     fi
 
 	CERT_BASE_PATH=$(
-		docker inspect -f '{{ range .Mounts }}{{ if and (eq .Type "bind") (eq .Destination "/opt/cloudbeaver/conf/certificates") }}\
-		{{ .Source }}{{ end }}{{ end }}' "$PROJECT_NAME-cloudbeaver-te-1"
+		docker inspect -f '{{ range .Mounts }}{{ if and (eq .Type "bind") (eq .Destination "/opt/cloudbeaver/conf/certificates") }}{{ .Source }}{{ end }}{{ end }}' \
+		"$PROJECT_NAME-cloudbeaver-te-1"
 	)
-    CERT_PATH="${CERT_BASE_PATH%/*}"  
-    CERT_ARCHIVE_PATH="$BACKUP_DIR/cert.tar.gz"
-    if [ -f "$CERT_ARCHIVE_PATH" ]; then
-        echo "Restoring certificates to $CERT_PATH"
-        tar -xzvf $CERT_ARCHIVE_PATH -C $CERT_PATH
-    else
-        echo "Certificates backup $CERT_ARCHIVE_PATH not found."
-    fi
 
+	CERT_ARCHIVE_PATH="$BACKUP_DIR/cert.tar.gz"
+	if [ -n "$CERT_BASE_PATH" ] && [ -f "$CERT_ARCHIVE_PATH" ]; then
+		echo "Restoring certificates to $CERT_BASE_PATH"
+		tar -xzvf "$CERT_ARCHIVE_PATH" -C "$CERT_BASE_PATH" || { 
+			echo "Error restoring certificates!"
+			printSupportMessage
+			exit 1
+		}
+	else
+		echo "Certificates backup or path not found."
+		printSupportMessage
+		exit 1
+	fi
+
+	CERT_ARCHIVE_PATH="$BACKUP_DIR/trusted-cacerts.tar.gz"
+	TRUSTED_CERT_VOLUME_PATH="/opt/cloudbeaver/conf/certificates/custom"
+	TE_CONTAINER="$PROJECT_NAME-cloudbeaver-te-1"
+
+	if [ -f "$CERT_ARCHIVE_PATH" ] && [ -s "$CERT_ARCHIVE_PATH" ]; then
+		echo "Restoring TE trusted certificates..."
+
+		docker cp "$CERT_ARCHIVE_PATH" "$TE_CONTAINER:/tmp/trusted-cacerts.tar.gz"
+
+		docker compose exec -T cloudbeaver-te \
+			tar -xzf "/tmp/trusted-cacerts.tar.gz" -C "$TRUSTED_CERT_VOLUME_PATH" || { 
+				echo "Error restoring TE trusted certificates!"
+				printSupportMessage
+				exit 1
+			}
+
+		docker compose exec -T cloudbeaver-te rm -f "/tmp/trusted-cacerts.tar.gz"
+	else
+		echo "TE trusted certificates archive not found or empty. Skipping restore (this is OK)."
+	fi
+	
     rm -rf $TEMP_DIR
     docker compose -f /opt/dbeaver-team-server/team-edition-deploy/compose/cbte/docker-compose.yml down 
     docker compose \
