dbeaver/dbeaver-devops#1810 Migrated compose-config-editor.py in te-d… (#141)
* dbeaver/dbeaver-devops#1810 Migrated compose-config-editor.py in te-deploy repo and run it during update

* dbeaver/dbeaver-devops#1810 Changed location compose-config-editor.py and added it in instal-manager

* dbeaver/dbeaver-devops#1810 Added validate error for compose-config-editor and change time format

* dbeaver/dbeaver-devops#1810 Changed script name to dbeaver-compose-config-editor.py

* dbeaver/dbeaver-devops#1810 Added configuration docker compose volumes during update

diff --git a/manager/dbeaver-te b/manager/dbeaver-te
--- a/manager/dbeaver-te
+++ b/manager/dbeaver-te
@@ -274,7 +274,7 @@ updateCloudbeaver() {
     checkCloudBeaverUpdateVersion "$1" 
     
     if [ "$TEAM_EDITION_UPDATE_AVAILABLE" == true ]; then
-        TIMESTAMP=$(date +%Y-%m-%d_%H-%M)
+        TIMESTAMP=$(date +%m-%d-%Y_%H-%M)
         BACKUP_DIR="/opt/dbeaver-team-server/team-edition-deploy-${TEAM_EDITION_TAG}-${TIMESTAMP}"
         
         # Check if user has write permission for /opt/dbeaver-team-server/team-edition-deploy/
@@ -337,6 +337,21 @@ updateCloudbeaver() {
             /opt/dbeaver-team-server/team-edition-deploy/compose/cbte/.env
         
         export CLOUDBEAVER_VERSION_TAG=$TEAM_EDITION_NEW_TAG
+        
+        # Update docker-compose volumes
+
+        if [ $DBEAVER_TEAM_EDITION_AMI ]; then
+            /usr/local/bin/dbeaver-compose-config-editor.py \
+                -f /opt/dbeaver-team-server/team-edition-deploy/compose/cbte/docker-compose.yml \
+                -e /opt/dbeaver-team-server/team-edition-deploy/compose/cbte/.env || {
+                    echo "==============================================================================="
+                    echo "Error: Failed to patch docker-compose.yml using dbeaver-compose-config-editor.py."
+                    echo "==============================================================================="
+                    rollbackCloudBeaver "$BACKUP_DIR" "$TEAM_EDITION_TAG"
+                    printSupportMessage
+                    exit 1
+                }
+        fi
         
         # Start team-edition-deploy with new version and check status
         docker compose \
