dbeaver/dbeaver-devops#1810 Changed logic of backup and restore certs

diff --git a/manager/dbeaver-te b/manager/dbeaver-te
--- a/manager/dbeaver-te
+++ b/manager/dbeaver-te
@@ -401,22 +401,11 @@ createBackup(){
         DB_NAME="cloudbeaver"
         docker exec $PROJECT_NAME-"$PG_SERVICE"-1 pg_dump $DB_NAME --username $CLOUDBEAVER_DB_USER --format c > $BACKUP_PATH/"$PG_SERVICE".backup
     fi
-
-	CERT_BASE_PATH=$(docker inspect "$DC_CONTAINER" | jq -r '
-		.[0].Mounts[] | select(.Type=="bind" and .Destination=="/opt/domain-controller/conf/certificates").Source
-	')
-	if [ -z "$CERT_BASE_PATH" ]; then
-		echo "ERROR: CERT_BASE_PATH not found!"
-		exit 1
-	fi
-
-	CERT_PATH="${CERT_BASE_PATH%/*}"
-	tar -czf "$BACKUP_PATH/cert.tar.gz" -C "$CERT_PATH" .
-
-	TRUSTED_CERT_VOLUME_PATH="/opt/domain-controller/conf/certificates/custom"
-	docker exec "$DC_CONTAINER" sh -c \
-		"if [ -d '${TRUSTED_CERT_VOLUME_PATH}' ] && [ \"\$(ls -A '${TRUSTED_CERT_VOLUME_PATH}')\" ]; then tar -czf - -C '${TRUSTED_CERT_VOLUME_PATH}' .; fi" \
-		> "$BACKUP_PATH/trusted-cacerts.tar.gz"
+    
+    CERT_VOLUME_PATH="/opt/domain-controller/conf/certificates"
+    
+    docker exec "$DC_CONTAINER" tar -czf /tmp/cert.tar.gz -C "$CERT_VOLUME_PATH" .
+    docker cp "$DC_CONTAINER:/tmp/cert.tar.gz" "$BACKUP_PATH/cert.tar.gz"
 
     tar -czf "$BACKUP_PATH".tar.gz $BACKUP_PATH
 }
@@ -468,41 +457,22 @@ restoreBackup(){
 	CERT_BASE_PATH=$(
 		docker inspect -f '{{ range .Mounts }}{{ if and (eq .Type "bind") (eq .Destination "/opt/domain-controller/conf/certificates") }}{{ .Source }}{{ end }}{{ end }}' \
 		"$DC_CONTAINER"
-	)
-
-	CERT_ARCHIVE_PATH="$BACKUP_DIR/cert.tar.gz"
-	if [ -n "$CERT_BASE_PATH" ] && [ -f "$CERT_ARCHIVE_PATH" ]; then
-		echo "Restoring certificates to $CERT_BASE_PATH"
-		tar -xzvf "$CERT_ARCHIVE_PATH" -C "$CERT_BASE_PATH" || { 
-			echo "Error restoring certificates!"
-			printSupportMessage
-			exit 1
-		}
-	else
-		echo "Certificates backup or path not found."
-		printSupportMessage
-		exit 1
-	fi
-
-	CERT_ARCHIVE_PATH="$BACKUP_DIR/trusted-cacerts.tar.gz"
-	TRUSTED_CERT_VOLUME_PATH="/opt/domain-controller/conf/certificates/custom"
-
-	if [ -f "$CERT_ARCHIVE_PATH" ] && [ -s "$CERT_ARCHIVE_PATH" ]; then
-		echo "Restoring TE trusted certificates..."
-
-		docker cp "$CERT_ARCHIVE_PATH" "$DC_CONTAINER:/tmp/trusted-cacerts.tar.gz"
-
-		docker exec "$PROJECT_NAME-$SERVICE-1" \
-			tar -xzf "/tmp/trusted-cacerts.tar.gz" -C "$TRUSTED_CERT_VOLUME_PATH" || { 
-				echo "Error restoring TE trusted certificates!"
-				printSupportMessage
-				exit 1
-			}
-
-		docker exec "$DC_CONTAINER" rm -f "/tmp/trusted-cacerts.tar.gz"
-	else
-		echo "TE trusted certificates archive not found or empty. Skipping restore (this is OK)."
-	fi
+    )
+    
+    CERT_ARCHIVE_PATH="$BACKUP_DIR/cert.tar.gz"
+    if [ -n "$CERT_BASE_PATH" ] && [ -f "$CERT_ARCHIVE_PATH" ]; then
+    	echo "Restoring all certificates to $CERT_BASE_PATH..."
+        docker cp "$CERT_ARCHIVE_PATH" "$DC_CONTAINER:/tmp/cert.tar.gz"
+    	docker exec "$DC_CONTAINER" sh -c "tar -xzvf /tmp/cert.tar.gz -C /opt/domain-controller/conf/certificates && rm -f /tmp/cert.tar.gz" || { 
+    		echo "Error restoring certificates!"
+    		printSupportMessage
+    		exit 1
+    	}
+    else
+    	echo "Certificates backup or path not found."
+    	printSupportMessage
+    	exit 1
+    fi
 	
     rm -rf $TEMP_DIR
     docker compose -f /opt/dbeaver-team-server/team-edition-deploy/compose/cbte/docker-compose.yml down 
