dbeaver/dbeaver-devops#1810 Fixed tabs

diff --git a/manager/dbeaver-te b/manager/dbeaver-te
--- a/manager/dbeaver-te
+++ b/manager/dbeaver-te
@@ -262,45 +262,45 @@ rollbackCloudBeaver() {
 
 updateCloudbeaver() {
     [ "$(docker ps -a | grep $TEAM_EDITION_IMAGE)" ]
-	# Check if update is available
+    # Check if update is available
     checkCloudBeaverUpdateVersion "$1" 
     
     if [ "$TEAM_EDITION_UPDATE_AVAILABLE" == true ]; then
         TIMESTAMP=$(date +%Y-%m-%d_%H-%M)
         BACKUP_DIR="/opt/dbeaver-team-server/team-edition-deploy-${TEAM_EDITION_TAG}-${TIMESTAMP}"
-
+        
         # Stop team-edition-deploy and backup current configuration
-		docker compose \
+        docker compose \
             -f /opt/dbeaver-team-server/team-edition-deploy/compose/cbte/docker-compose.yml \
             --env-file /opt/dbeaver-team-server/team-edition-deploy/compose/cbte/.env \
             --project-directory /opt/dbeaver-team-server/team-edition-deploy/compose/cbte/ \
             down \
             --remove-orphans
-		mkdir -p $BACKUP_DIR
+        mkdir -p $BACKUP_DIR
         rsync -av --exclude='cert' --exclude='nginx' /opt/dbeaver-team-server/team-edition-deploy/compose/cbte/ "$BACKUP_DIR"
-		echo "Preveous team-edition-deploy configuration copied to $BACKUP_DIR"
-
-		# Checkout to new version
+        echo "Preveous team-edition-deploy configuration copied to $BACKUP_DIR"
+        
+        # Checkout to new version
         cd /opt/dbeaver-team-server/team-edition-deploy/
-		git fetch || { 
-			echo "Error: Failed to fetch latest changes from repository. Rolling back to previous version..."
-			rollbackCloudBeaver "$BACKUP_DIR" "$TEAM_EDITION_TAG"
-		}
-		git checkout --force $TEAM_EDITION_NEW_TAG || { 
-			echo "Error: Failed to checkout version $TEAM_EDITION_NEW_TAG. Rolling back to previous version..."
-			rollbackCloudBeaver "$BACKUP_DIR" "$TEAM_EDITION_TAG"
-		}
+        git fetch || { 
+        	echo "Error: Failed to fetch latest changes from repository. Rolling back to previous version..."
+        	rollbackCloudBeaver "$BACKUP_DIR" "$TEAM_EDITION_TAG"
+        }
+        git checkout --force $TEAM_EDITION_NEW_TAG || { 
+        	echo "Error: Failed to checkout version $TEAM_EDITION_NEW_TAG. Rolling back to previous version..."
+        	rollbackCloudBeaver "$BACKUP_DIR" "$TEAM_EDITION_TAG"
+        }
         sed -i "s/CLOUDBEAVER_VERSION_TAG=$TEAM_EDITION_TAG/CLOUDBEAVER_VERSION_TAG=$TEAM_EDITION_NEW_TAG/g" /opt/dbeaver-team-server/team-edition-deploy/compose/cbte/.env 
         export CLOUDBEAVER_VERSION_TAG=$TEAM_EDITION_NEW_TAG
-
-		# Start team-edition-deploy with new version and check status
-		docker compose \
-			-f /opt/dbeaver-team-server/team-edition-deploy/compose/cbte/docker-compose.yml \
-			--env-file /opt/dbeaver-team-server/team-edition-deploy/compose/cbte/.env \
-			--project-directory /opt/dbeaver-team-server/team-edition-deploy/compose/cbte/ \
-			up -d \
-			--remove-orphans \
-			--pull always
+        
+        # Start team-edition-deploy with new version and check status
+        docker compose \
+        	-f /opt/dbeaver-team-server/team-edition-deploy/compose/cbte/docker-compose.yml \
+        	--env-file /opt/dbeaver-team-server/team-edition-deploy/compose/cbte/.env \
+        	--project-directory /opt/dbeaver-team-server/team-edition-deploy/compose/cbte/ \
+        	up -d \
+        	--remove-orphans \
+        	--pull always
         
         TEAM_EDITION_STATUS_RETRY=300
         until [ $TEAM_EDITION_STATUS_RETRY -lt 0 ]; do
@@ -409,12 +409,12 @@ restoreBackup(){
     fi
 
     rm -rf $TEMP_DIR
-	docker compose -f /opt/dbeaver-team-server/team-edition-deploy/compose/cbte/docker-compose.yml down 
-	docker compose \
-		-f /opt/dbeaver-team-server/team-edition-deploy/compose/cbte/docker-compose.yml \
-		--env-file /opt/dbeaver-team-server/team-edition-deploy/compose/cbte/.env \
-		--project-directory /opt/dbeaver-team-server/team-edition-deploy/compose/cbte/ \
-		up -d
+    docker compose -f /opt/dbeaver-team-server/team-edition-deploy/compose/cbte/docker-compose.yml down 
+    docker compose \
+        -f /opt/dbeaver-team-server/team-edition-deploy/compose/cbte/docker-compose.yml \
+        --env-file /opt/dbeaver-team-server/team-edition-deploy/compose/cbte/.env \
+        --project-directory /opt/dbeaver-team-server/team-edition-deploy/compose/cbte/ \
+        up -d
 }
 
 case $1 in
